### ISSUE TITLE
Unchecked memory reference

### ISSUE THREAD

**Issue by dianestephens** [Chinmaykd21/CSCI8000_Project_Compiler#17]
The following vulnerability was detected by the AFL fuzzer.
The input program:
```
    int even(int in, st msg){
    if(in % 2){
        strcpy(msg, " is even");
    }
    else if(in < 0)
    {
        strcpy(msg, " is negative");
    }
    else{
        strcpy(msg, " do not knowjj");
    }
    return 0;
}
int main()
{
    int a, b, c;
    string msg;
    scanf("%d%d%f", &a, &b, &c);
    return even(a, msg);
   
}
```
Vulnerable locations as reported in the debug backtrace of the crash:
```
(gdb) r id:000006,sig:11,src:000000,op:flip1,pos:15
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/dianestephens/CSCI8000_Project_Compiler-main/compiler id:000006,sig:11,src:000000,op:flip1,pos:15
function even
- return int
- param int in�
openParNum: 8
-- if in  2
--- call fn strcpy

Program received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (
    this=0x7fffffffd0f8, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
__str=)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:451
451	      { _M_construct(__str._M_data(), __str._M_data() + __str.length()); }
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (
    this=0x7fffffffd0f8, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
__str=)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:451
#1  parseTree (start=<optimized out>, end=29, tokens=..., 
    parenthesisMap=std::unordered_map with 14 elements = {...}, varTypeMap=..., indent=<incomplete type>)
    at parseTree.cpp:309
#2  0x000000000043c69e in parseTree (start=<optimized out>, end=75, tokens=..., 
    parenthesisMap=std::unordered_map with 14 elements = {...}, varTypeMap=..., indent=<incomplete type>)
    at parseTree.cpp:152
#3  0x00000000004392aa in parseTree (start=<optimized out>, end=121, tokens=..., 
    parenthesisMap=std::unordered_map with 14 elements = {...}, varTypeMap=..., indent=<incomplete type>)
    at parseTree.cpp:84
#4  0x00000000004040a6 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:38

```

The source code reported vulnerable in parseTree.cpp at line 309: An unchecked key value from tokens[j] above:

```
    else
                                {
                                    //cout << "II" << endl;
                                    key = tokens[j];
                                }
                               // cout << "key: " << key << endl;
                                auto it1 = newVarTypeMap.find(key);
                                 //cout << "VI" << endl;
                                //cout << it1->second << endl;
   309 -->                  string type = it1->second;
     				  cout << indent << " arg " << type << " " << key << endl;

```
The same location resulted in multiple crashes.  Another is included below:
```
(gdb) r id:000028,sig:11,src:000000,op:flip1,pos:114
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/dianestephens/CSCI8000_Project_Compiler-main/compiler id:000028,sig:11,src:000000,op:flip1,pos:114
function even
- return int
- param int in
- param st msg
openParNum: 9
-- if in  2
--- call fn strcpy
---- arg st msg
---- arg  string "iseven"
-- else if in lt 0
--- call fn strcpy

Program received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (
    this=0x7fffffffd0f8, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
__str=)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:451
451	      { _M_construct(__str._M_data(), __str._M_data() + __str.length()); }


(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (
    this=0x7fffffffd0f8, Python Exception <class 'gdb.error'> There is no member named _M_dataplus.: 
__str=)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/basic_string.h:451
#1  parseTree (start=<optimized out>, end=53, tokens=..., 
    parenthesisMap=std::unordered_map with 14 elements = {...}, varTypeMap=..., indent=<incomplete type>)
    at parseTree.cpp:309
#2  0x000000000043f5fe in parseTree (start=<optimized out>, end=76, tokens=..., 
    parenthesisMap=std::unordered_map with 14 elements = {...}, varTypeMap=..., indent=<incomplete type>)
    at parseTree.cpp:211
#3  0x00000000004392aa in parseTree (start=<optimized out>, end=122, tokens=..., 
    parenthesisMap=std::unordered_map with 14 elements = {...}, varTypeMap=..., indent=<incomplete type>)
    at parseTree.cpp:84
#4  0x00000000004040a6 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:38
(gdb) 

Debug from this code:
dianestephens@ubuntu:~/CSCI8000_Project_Compiler-main$ ./compiler afl_inD/testD.cpp
function even
- return int
- param int in
- param st msg
openParNum: 9
-- if in  2
--- call fn strcpy
tokens[j]: msg it1->second: st
---- arg st msg
---- arg  string "iseven"
-- else if in lt 0
--- call fn strcpy
tokens[j]: msg it1->second: st
---- arg st msg
---- arg  string "isnegative"
-- else
--- call fn strcpy
tokens[j]: msg it1->second: st
---- arg st msg
---- arg  string "donotknowjj"

function main
- return int
openParNum: 83
-- local int a
-- local int b
-- local int c
-- call fn scanf
--- arg  string "%d%d%f"
tokens[j]: &a it1->second: int
--- arg int a
tokens[j]: &b it1->second: int
--- arg int b
tokens[j]: &c it1->second: int
--- arg int c
-- call fn even
tokens[j]: a it1->second: int
--- arg int a
tokens[j]: msg it1->second: st
--- arg st msg

````

**Comment by mustakimur** [comment]
@ChinmayDeosthali @Chinmaykd21  please commit the fix for the issue and comment the commit number here.

**Comment by ChinmayDeosthali** [comment]
We have applied the following check at the lines-84,152,211,309 in parsetree.cpp:

if(it1 != newVarTypeMap.end()){
  string type = it1->second;
  cout << indent << " arg " << type << " " << key << endl;
}

This should take care of the issue. Please let us know if you have any questions.
